import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@radix-ui/themes/styles.css';

import { Theme } from '@radix-ui/themes';
import { AI } from "./actions";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AI>
    <html lang="en">
      <body className={inter.className}>
      <Theme appearance="dark">
      {children}
      </Theme>
      </body>
    </html>
    </AI>
  );
}
